// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: api/conduit/v1/conduit.proto

package v1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NID_REGIDTER_REQ
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Res           *Res                   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterReply) GetRes() *Res {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *RegisterReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// NID_LOGIN_REQ
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=成功, 1=失败
	Res           *Res                   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`    // 业务信息
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginReply) GetRes() *Res {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// NID_UPDATE_REQ
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdateRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0=成功, 1=失败
	Res           *Res                   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`    // 业务信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReply) Reset() {
	*x = UpdateReply{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReply) ProtoMessage() {}

func (x *UpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReply.ProtoReflect.Descriptor instead.
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateReply) GetRes() *Res {
	if x != nil {
		return x.Res
	}
	return nil
}

// Social 相关协议
// NID_GET_PROFILE_REQ
type ProfileData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tags              string                 `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	FollowCount       uint32                 `protobuf:"varint,4,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"`
	FanCount          uint32                 `protobuf:"varint,5,opt,name=fan_count,json=fanCount,proto3" json:"fan_count,omitempty"`
	ViewCount         uint32                 `protobuf:"varint,6,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	NoteCount         uint32                 `protobuf:"varint,7,opt,name=note_count,json=noteCount,proto3" json:"note_count,omitempty"`
	ReceivedLikeCount uint32                 `protobuf:"varint,8,opt,name=received_like_count,json=receivedLikeCount,proto3" json:"received_like_count,omitempty"`
	CollectedCount    uint32                 `protobuf:"varint,9,opt,name=collected_count,json=collectedCount,proto3" json:"collected_count,omitempty"`
	CommentCount      uint32                 `protobuf:"varint,10,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	LastLoginIp       string                 `protobuf:"bytes,11,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`
	LastActive        *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	Status            string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProfileData) Reset() {
	*x = ProfileData{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileData) ProtoMessage() {}

func (x *ProfileData) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileData.ProtoReflect.Descriptor instead.
func (*ProfileData) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileData) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProfileData) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *ProfileData) GetFollowCount() uint32 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *ProfileData) GetFanCount() uint32 {
	if x != nil {
		return x.FanCount
	}
	return 0
}

func (x *ProfileData) GetViewCount() uint32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ProfileData) GetNoteCount() uint32 {
	if x != nil {
		return x.NoteCount
	}
	return 0
}

func (x *ProfileData) GetReceivedLikeCount() uint32 {
	if x != nil {
		return x.ReceivedLikeCount
	}
	return 0
}

func (x *ProfileData) GetCollectedCount() uint32 {
	if x != nil {
		return x.CollectedCount
	}
	return 0
}

func (x *ProfileData) GetCommentCount() uint32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *ProfileData) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *ProfileData) GetLastActive() *timestamp.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

func (x *ProfileData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// NID_GET_PROFILE_REQ
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Res           *Res                   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
	Data          *ProfileData           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReply) Reset() {
	*x = GetProfileReply{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReply) ProtoMessage() {}

func (x *GetProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReply.ProtoReflect.Descriptor instead.
func (*GetProfileReply) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetProfileReply) GetRes() *Res {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *GetProfileReply) GetData() *ProfileData {
	if x != nil {
		return x.Data
	}
	return nil
}

// NID_FOLLOW_FAN_REQ
type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{9}
}

func (x *FollowUserRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type UnfollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{10}
}

func (x *UnfollowUserRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type FollowFanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Res           *Res                   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
	Data          *FollowFanData         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowFanReply) Reset() {
	*x = FollowFanReply{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowFanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowFanReply) ProtoMessage() {}

func (x *FollowFanReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowFanReply.ProtoReflect.Descriptor instead.
func (*FollowFanReply) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{11}
}

func (x *FollowFanReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FollowFanReply) GetRes() *Res {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *FollowFanReply) GetData() *FollowFanData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FollowFanData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前用户信息
	SelfId      uint32 `protobuf:"varint,1,opt,name=self_id,json=selfId,proto3" json:"self_id,omitempty"`
	FollowCount uint32 `protobuf:"varint,2,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"` // 我的关注数
	// 对方用户信息
	TargetId      uint32 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	FanCount      uint32 `protobuf:"varint,4,opt,name=fan_count,json=fanCount,proto3" json:"fan_count,omitempty"` // 对方的粉丝数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowFanData) Reset() {
	*x = FollowFanData{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowFanData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowFanData) ProtoMessage() {}

func (x *FollowFanData) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowFanData.ProtoReflect.Descriptor instead.
func (*FollowFanData) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{12}
}

func (x *FollowFanData) GetSelfId() uint32 {
	if x != nil {
		return x.SelfId
	}
	return 0
}

func (x *FollowFanData) GetFollowCount() uint32 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *FollowFanData) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *FollowFanData) GetFanCount() uint32 {
	if x != nil {
		return x.FanCount
	}
	return 0
}

type RelationshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipRequest) Reset() {
	*x = RelationshipRequest{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipRequest) ProtoMessage() {}

func (x *RelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipRequest.ProtoReflect.Descriptor instead.
func (*RelationshipRequest) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{13}
}

func (x *RelationshipRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type RelationshipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Res           *Res                   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
	Data          *RelationshipData      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipReply) Reset() {
	*x = RelationshipReply{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipReply) ProtoMessage() {}

func (x *RelationshipReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipReply.ProtoReflect.Descriptor instead.
func (*RelationshipReply) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{14}
}

func (x *RelationshipReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RelationshipReply) GetRes() *Res {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *RelationshipReply) GetData() *RelationshipData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RelationshipData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollowing   bool                   `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`      // 当前用户是否已关注对方
	IsFollowedBy  bool                   `protobuf:"varint,2,opt,name=is_followed_by,json=isFollowedBy,proto3" json:"is_followed_by,omitempty"` // 当前用户是否被对方关注
	IsMutual      bool                   `protobuf:"varint,3,opt,name=is_mutual,json=isMutual,proto3" json:"is_mutual,omitempty"`               // 是否互相关注
	IsBlocked     bool                   `protobuf:"varint,4,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`            // 当前用户是否已拉黑对方
	IsBlockedBy   bool                   `protobuf:"varint,5,opt,name=is_blocked_by,json=isBlockedBy,proto3" json:"is_blocked_by,omitempty"`    // 当前用户是否被对方拉黑
	IsFriend      bool                   `protobuf:"varint,6,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`               // 是否是好友（如果互关=好友，可以合并，目前互关和好友不是等价的）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipData) Reset() {
	*x = RelationshipData{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipData) ProtoMessage() {}

func (x *RelationshipData) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipData.ProtoReflect.Descriptor instead.
func (*RelationshipData) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{15}
}

func (x *RelationshipData) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

func (x *RelationshipData) GetIsFollowedBy() bool {
	if x != nil {
		return x.IsFollowedBy
	}
	return false
}

func (x *RelationshipData) GetIsMutual() bool {
	if x != nil {
		return x.IsMutual
	}
	return false
}

func (x *RelationshipData) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *RelationshipData) GetIsBlockedBy() bool {
	if x != nil {
		return x.IsBlockedBy
	}
	return false
}

func (x *RelationshipData) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

// NID_FRIENDS_REQ
type CanAddFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanAddFriendReq) Reset() {
	*x = CanAddFriendReq{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanAddFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanAddFriendReq) ProtoMessage() {}

func (x *CanAddFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanAddFriendReq.ProtoReflect.Descriptor instead.
func (*CanAddFriendReq) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{16}
}

func (x *CanAddFriendReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type CanAddFriendRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Res           *Res                   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
	Data          *AddFriendRes          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanAddFriendRes) Reset() {
	*x = CanAddFriendRes{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanAddFriendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanAddFriendRes) ProtoMessage() {}

func (x *CanAddFriendRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanAddFriendRes.ProtoReflect.Descriptor instead.
func (*CanAddFriendRes) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{17}
}

func (x *CanAddFriendRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CanAddFriendRes) GetRes() *Res {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *CanAddFriendRes) GetData() *AddFriendRes {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddFriendRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendRes) Reset() {
	*x = AddFriendRes{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendRes) ProtoMessage() {}

func (x *AddFriendRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendRes.ProtoReflect.Descriptor instead.
func (*AddFriendRes) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{18}
}

// 前端错误信息查看
// NID_Describe_Message
type Res struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`    // 业务状态码，例如 200、422
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 原因
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`       // 详细描述信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Res) Reset() {
	*x = Res{}
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_api_conduit_v1_conduit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_api_conduit_v1_conduit_proto_rawDescGZIP(), []int{19}
}

func (x *Res) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Res) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Res) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_conduit_v1_conduit_proto protoreflect.FileDescriptor

const file_api_conduit_v1_conduit_proto_rawDesc = "" +
	"\n" +
	"\x1capi/conduit/v1/conduit.proto\x12\frealworld.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"^\n" +
	"\rRegisterReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12#\n" +
	"\x03res\x18\x02 \x01(\v2\x11.realworld.v1.ResR\x03res\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"[\n" +
	"\n" +
	"LoginReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12#\n" +
	"\x03res\x18\x02 \x01(\v2\x11.realworld.v1.ResR\x03res\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"k\n" +
	"\rUpdateRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"F\n" +
	"\vUpdateReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12#\n" +
	"\x03res\x18\x02 \x01(\v2\x11.realworld.v1.ResR\x03res\"\xaf\x03\n" +
	"\vProfileData\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x12\n" +
	"\x04tags\x18\x03 \x01(\tR\x04tags\x12!\n" +
	"\ffollow_count\x18\x04 \x01(\rR\vfollowCount\x12\x1b\n" +
	"\tfan_count\x18\x05 \x01(\rR\bfanCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x06 \x01(\rR\tviewCount\x12\x1d\n" +
	"\n" +
	"note_count\x18\a \x01(\rR\tnoteCount\x12.\n" +
	"\x13received_like_count\x18\b \x01(\rR\x11receivedLikeCount\x12'\n" +
	"\x0fcollected_count\x18\t \x01(\rR\x0ecollectedCount\x12#\n" +
	"\rcomment_count\x18\n" +
	" \x01(\rR\fcommentCount\x12\"\n" +
	"\rlast_login_ip\x18\v \x01(\tR\vlastLoginIp\x12;\n" +
	"\vlast_active\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"y\n" +
	"\x0fGetProfileReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12#\n" +
	"\x03res\x18\x02 \x01(\v2\x11.realworld.v1.ResR\x03res\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.realworld.v1.ProfileDataR\x04data\"0\n" +
	"\x11FollowUserRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"2\n" +
	"\x13UnfollowUserRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"z\n" +
	"\x0eFollowFanReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12#\n" +
	"\x03res\x18\x02 \x01(\v2\x11.realworld.v1.ResR\x03res\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.realworld.v1.FollowFanDataR\x04data\"\x85\x01\n" +
	"\rFollowFanData\x12\x17\n" +
	"\aself_id\x18\x01 \x01(\rR\x06selfId\x12!\n" +
	"\ffollow_count\x18\x02 \x01(\rR\vfollowCount\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\rR\btargetId\x12\x1b\n" +
	"\tfan_count\x18\x04 \x01(\rR\bfanCount\"2\n" +
	"\x13RelationshipRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"\x80\x01\n" +
	"\x11RelationshipReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12#\n" +
	"\x03res\x18\x02 \x01(\v2\x11.realworld.v1.ResR\x03res\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x1e.realworld.v1.RelationshipDataR\x04data\"\xd8\x01\n" +
	"\x10RelationshipData\x12!\n" +
	"\fis_following\x18\x01 \x01(\bR\visFollowing\x12$\n" +
	"\x0eis_followed_by\x18\x02 \x01(\bR\fisFollowedBy\x12\x1b\n" +
	"\tis_mutual\x18\x03 \x01(\bR\bisMutual\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x04 \x01(\bR\tisBlocked\x12\"\n" +
	"\ris_blocked_by\x18\x05 \x01(\bR\visBlockedBy\x12\x1b\n" +
	"\tis_friend\x18\x06 \x01(\bR\bisFriend\".\n" +
	"\x0fCanAddFriendReq\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"z\n" +
	"\x0fCanAddFriendRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12#\n" +
	"\x03res\x18\x02 \x01(\v2\x11.realworld.v1.ResR\x03res\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.realworld.v1.AddFriendResR\x04data\"\x0e\n" +
	"\fAddFriendRes\"C\n" +
	"\x03Res\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg2\xa6\a\n" +
	"\aConduit\x12]\n" +
	"\bRegister\x12\x1d.realworld.v1.RegisterRequest\x1a\x1b.realworld.v1.RegisterReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/users\x12Z\n" +
	"\x05Login\x12\x1a.realworld.v1.LoginRequest\x1a\x18.realworld.v1.LoginReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/users/login\x12n\n" +
	"\x0eUpdatePassword\x12\x1b.realworld.v1.UpdateRequest\x1a\x19.realworld.v1.UpdateReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/users/updatePassword\x12m\n" +
	"\n" +
	"GetProfile\x12\x1f.realworld.v1.GetProfileRequest\x1a\x1d.realworld.v1.GetProfileReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/profiles/{user_id}\x12x\n" +
	"\n" +
	"FollowUser\x12\x1f.realworld.v1.FollowUserRequest\x1a\x1c.realworld.v1.FollowFanReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/profiles/{target_id}/follow\x12~\n" +
	"\fUnfollowUser\x12!.realworld.v1.UnfollowUserRequest\x1a\x1c.realworld.v1.FollowFanReply\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/profiles/{target_id}/unfollow\x12\x85\x01\n" +
	"\x0fGetRelationship\x12!.realworld.v1.RelationshipRequest\x1a\x1f.realworld.v1.RelationshipReply\".\x82\xd3\xe4\x93\x02(\x12&/api/profiles/{target_id}/relationship\x12\x7f\n" +
	"\fCanAddFriend\x12\x1d.realworld.v1.CanAddFriendReq\x1a\x1d.realworld.v1.CanAddFriendRes\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/profiles/{target_id}/canAddFriendB$Z\"kratos-realworld/api/conduit/v1;v1b\x06proto3"

var (
	file_api_conduit_v1_conduit_proto_rawDescOnce sync.Once
	file_api_conduit_v1_conduit_proto_rawDescData []byte
)

func file_api_conduit_v1_conduit_proto_rawDescGZIP() []byte {
	file_api_conduit_v1_conduit_proto_rawDescOnce.Do(func() {
		file_api_conduit_v1_conduit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conduit_v1_conduit_proto_rawDesc), len(file_api_conduit_v1_conduit_proto_rawDesc)))
	})
	return file_api_conduit_v1_conduit_proto_rawDescData
}

var file_api_conduit_v1_conduit_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_conduit_v1_conduit_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: realworld.v1.RegisterRequest
	(*RegisterReply)(nil),       // 1: realworld.v1.RegisterReply
	(*LoginRequest)(nil),        // 2: realworld.v1.LoginRequest
	(*LoginReply)(nil),          // 3: realworld.v1.LoginReply
	(*UpdateRequest)(nil),       // 4: realworld.v1.UpdateRequest
	(*UpdateReply)(nil),         // 5: realworld.v1.UpdateReply
	(*ProfileData)(nil),         // 6: realworld.v1.ProfileData
	(*GetProfileRequest)(nil),   // 7: realworld.v1.GetProfileRequest
	(*GetProfileReply)(nil),     // 8: realworld.v1.GetProfileReply
	(*FollowUserRequest)(nil),   // 9: realworld.v1.FollowUserRequest
	(*UnfollowUserRequest)(nil), // 10: realworld.v1.UnfollowUserRequest
	(*FollowFanReply)(nil),      // 11: realworld.v1.FollowFanReply
	(*FollowFanData)(nil),       // 12: realworld.v1.FollowFanData
	(*RelationshipRequest)(nil), // 13: realworld.v1.RelationshipRequest
	(*RelationshipReply)(nil),   // 14: realworld.v1.RelationshipReply
	(*RelationshipData)(nil),    // 15: realworld.v1.RelationshipData
	(*CanAddFriendReq)(nil),     // 16: realworld.v1.CanAddFriendReq
	(*CanAddFriendRes)(nil),     // 17: realworld.v1.CanAddFriendRes
	(*AddFriendRes)(nil),        // 18: realworld.v1.AddFriendRes
	(*Res)(nil),                 // 19: realworld.v1.Res
	(*timestamp.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_api_conduit_v1_conduit_proto_depIdxs = []int32{
	19, // 0: realworld.v1.RegisterReply.res:type_name -> realworld.v1.Res
	19, // 1: realworld.v1.LoginReply.res:type_name -> realworld.v1.Res
	19, // 2: realworld.v1.UpdateReply.res:type_name -> realworld.v1.Res
	20, // 3: realworld.v1.ProfileData.last_active:type_name -> google.protobuf.Timestamp
	19, // 4: realworld.v1.GetProfileReply.res:type_name -> realworld.v1.Res
	6,  // 5: realworld.v1.GetProfileReply.data:type_name -> realworld.v1.ProfileData
	19, // 6: realworld.v1.FollowFanReply.res:type_name -> realworld.v1.Res
	12, // 7: realworld.v1.FollowFanReply.data:type_name -> realworld.v1.FollowFanData
	19, // 8: realworld.v1.RelationshipReply.res:type_name -> realworld.v1.Res
	15, // 9: realworld.v1.RelationshipReply.data:type_name -> realworld.v1.RelationshipData
	19, // 10: realworld.v1.CanAddFriendRes.res:type_name -> realworld.v1.Res
	18, // 11: realworld.v1.CanAddFriendRes.data:type_name -> realworld.v1.AddFriendRes
	0,  // 12: realworld.v1.Conduit.Register:input_type -> realworld.v1.RegisterRequest
	2,  // 13: realworld.v1.Conduit.Login:input_type -> realworld.v1.LoginRequest
	4,  // 14: realworld.v1.Conduit.UpdatePassword:input_type -> realworld.v1.UpdateRequest
	7,  // 15: realworld.v1.Conduit.GetProfile:input_type -> realworld.v1.GetProfileRequest
	9,  // 16: realworld.v1.Conduit.FollowUser:input_type -> realworld.v1.FollowUserRequest
	10, // 17: realworld.v1.Conduit.UnfollowUser:input_type -> realworld.v1.UnfollowUserRequest
	13, // 18: realworld.v1.Conduit.GetRelationship:input_type -> realworld.v1.RelationshipRequest
	16, // 19: realworld.v1.Conduit.CanAddFriend:input_type -> realworld.v1.CanAddFriendReq
	1,  // 20: realworld.v1.Conduit.Register:output_type -> realworld.v1.RegisterReply
	3,  // 21: realworld.v1.Conduit.Login:output_type -> realworld.v1.LoginReply
	5,  // 22: realworld.v1.Conduit.UpdatePassword:output_type -> realworld.v1.UpdateReply
	8,  // 23: realworld.v1.Conduit.GetProfile:output_type -> realworld.v1.GetProfileReply
	11, // 24: realworld.v1.Conduit.FollowUser:output_type -> realworld.v1.FollowFanReply
	11, // 25: realworld.v1.Conduit.UnfollowUser:output_type -> realworld.v1.FollowFanReply
	14, // 26: realworld.v1.Conduit.GetRelationship:output_type -> realworld.v1.RelationshipReply
	17, // 27: realworld.v1.Conduit.CanAddFriend:output_type -> realworld.v1.CanAddFriendRes
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_conduit_v1_conduit_proto_init() }
func file_api_conduit_v1_conduit_proto_init() {
	if File_api_conduit_v1_conduit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conduit_v1_conduit_proto_rawDesc), len(file_api_conduit_v1_conduit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_conduit_v1_conduit_proto_goTypes,
		DependencyIndexes: file_api_conduit_v1_conduit_proto_depIdxs,
		MessageInfos:      file_api_conduit_v1_conduit_proto_msgTypes,
	}.Build()
	File_api_conduit_v1_conduit_proto = out.File
	file_api_conduit_v1_conduit_proto_goTypes = nil
	file_api_conduit_v1_conduit_proto_depIdxs = nil
}
