version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-SoulChat
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chat_sql
    ports:
      - "5306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - soulchat-net

  redis:
    image: redis:6.2
    container_name: redis-SoulChat
    restart: always
    command: redis-server --requirepass 123456
    ports:
      - "5379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - soulchat-net

  zookeeper:
    image: zookeeper
    container_name: zookeeper-SoulChat
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - soulchat-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-SoulChat
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.218.131:9092 # 修正为正确的IP地址
      KAFKA_CREATE_TOPICS: "go-chat-message:2:1" # 修正为1个副本
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/data:/var/lib/kafka-logs
    networks:
      - soulchat-net

volumes:
  mysql_data:
  redis_data:
  kafka_data:

networks:
  soulchat-net:
    driver: bridge
