// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Jwt           *JWT                   `protobuf:"bytes,3,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Log           *Log                   `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	Sms           *Sms                   `protobuf:"bytes,5,opt,name=sms,proto3" json:"sms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetJwt() *JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetSms() *Sms {
	if x != nil {
		return x.Sms
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Dsn           string                 `protobuf:"bytes,3,opt,name=dsn,proto3" json:"dsn,omitempty"`
	Kafka         *Data_Kafka            `protobuf:"bytes,4,opt,name=kafka,proto3" json:"kafka,omitempty"`
	Storage       *Data_Storage          `protobuf:"bytes,5,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data) GetKafka() *Data_Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

func (x *Data) GetStorage() *Data_Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

type JWT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Expire        string                 `protobuf:"bytes,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWT) Reset() {
	*x = JWT{}
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWT) ProtoMessage() {}

func (x *JWT) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWT.ProtoReflect.Descriptor instead.
func (*JWT) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *JWT) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *JWT) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Director      string                 `protobuf:"bytes,1,opt,name=director,proto3" json:"director,omitempty"`                                // 日志目录，例如 ./logs
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`                                      // debug|info|warn|error|dpanic|panic|fatal
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`                                    // console|json
	StacktraceKey string                 `protobuf:"bytes,4,opt,name=stacktrace_key,json=stacktraceKey,proto3" json:"stacktrace_key,omitempty"` // 栈字段名，例如 stacktrace
	EncodeLevel   string                 `protobuf:"bytes,5,opt,name=encode_level,json=encodeLevel,proto3" json:"encode_level,omitempty"`       // LowercaseLevelEncoder|CapitalLevelEncoder 等
	LogInConsole  bool                   `protobuf:"varint,6,opt,name=log_in_console,json=logInConsole,proto3" json:"log_in_console,omitempty"` // 是否输出到控制台
	ShowLine      bool                   `protobuf:"varint,7,opt,name=show_line,json=showLine,proto3" json:"show_line,omitempty"`               // 是否显示调用行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Log) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Log) GetStacktraceKey() string {
	if x != nil {
		return x.StacktraceKey
	}
	return ""
}

func (x *Log) GetEncodeLevel() string {
	if x != nil {
		return x.EncodeLevel
	}
	return ""
}

func (x *Log) GetLogInConsole() bool {
	if x != nil {
		return x.LogInConsole
	}
	return false
}

func (x *Log) GetShowLine() bool {
	if x != nil {
		return x.ShowLine
	}
	return false
}

type Sms struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId      string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"` // 阿里云访问密钥
	AccessKeySecret  string                 `protobuf:"bytes,2,opt,name=access_key_secret,json=accessKeySecret,proto3" json:"access_key_secret,omitempty"`
	Endpoint         string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                             // 短信服务结点, 区分国内和国际
	SignName         string                 `protobuf:"bytes,4,opt,name=sign_name,json=signName,proto3" json:"sign_name,omitempty"`             // 短信签名
	TemplateCode     string                 `protobuf:"bytes,5,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"` // 短信模板CODE
	VerificationCode *Sms_VerificationCode  `protobuf:"bytes,6,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	RateLimit        *Sms_RateLimit         `protobuf:"bytes,7,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Retry            *Sms_Retry             `protobuf:"bytes,8,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Sms) Reset() {
	*x = Sms{}
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms) ProtoMessage() {}

func (x *Sms) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms.ProtoReflect.Descriptor instead.
func (*Sms) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Sms) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *Sms) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

func (x *Sms) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Sms) GetSignName() string {
	if x != nil {
		return x.SignName
	}
	return ""
}

func (x *Sms) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *Sms) GetVerificationCode() *Sms_VerificationCode {
	if x != nil {
		return x.VerificationCode
	}
	return nil
}

func (x *Sms) GetRateLimit() *Sms_RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *Sms) GetRetry() *Sms_Retry {
	if x != nil {
		return x.Retry
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Addr                     string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	User                     string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password                 string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database                 string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	MaxIdleConn              int32                  `protobuf:"varint,5,opt,name=max_idle_conn,json=maxIdleConn,proto3" json:"max_idle_conn,omitempty"`
	MaxOpenConn              int32                  `protobuf:"varint,6,opt,name=max_open_conn,json=maxOpenConn,proto3" json:"max_open_conn,omitempty"`
	MaxIdleTime              int32                  `protobuf:"varint,7,opt,name=max_idle_time,json=maxIdleTime,proto3" json:"max_idle_time,omitempty"`
	SlowThresholdMillisecond int64                  `protobuf:"varint,8,opt,name=slow_threshold_millisecond,json=slowThresholdMillisecond,proto3" json:"slow_threshold_millisecond,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Database) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Data_Database) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Database) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Data_Database) GetMaxIdleConn() int32 {
	if x != nil {
		return x.MaxIdleConn
	}
	return 0
}

func (x *Data_Database) GetMaxOpenConn() int32 {
	if x != nil {
		return x.MaxOpenConn
	}
	return 0
}

func (x *Data_Database) GetMaxIdleTime() int32 {
	if x != nil {
		return x.MaxIdleTime
	}
	return 0
}

func (x *Data_Database) GetSlowThresholdMillisecond() int64 {
	if x != nil {
		return x.SlowThresholdMillisecond
	}
	return 0
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	PoolSize      int32                  `protobuf:"varint,4,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Redis) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

type Data_Kafka struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         string                 `protobuf:"bytes,1,opt,name=hosts,proto3" json:"hosts,omitempty"`      // 多个地址用逗号分隔
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`      // 默认 topic 名称
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"` // 是否启用 kafka
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Kafka) Reset() {
	*x = Data_Kafka{}
	mi := &file_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Kafka) ProtoMessage() {}

func (x *Data_Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Kafka.ProtoReflect.Descriptor instead.
func (*Data_Kafka) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_Kafka) GetHosts() string {
	if x != nil {
		return x.Hosts
	}
	return ""
}

func (x *Data_Kafka) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Data_Kafka) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Data_Storage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaticDir     string                 `protobuf:"bytes,1,opt,name=static_dir,json=staticDir,proto3" json:"static_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Storage) Reset() {
	*x = Data_Storage{}
	mi := &file_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Storage) ProtoMessage() {}

func (x *Data_Storage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Storage.ProtoReflect.Descriptor instead.
func (*Data_Storage) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Data_Storage) GetStaticDir() string {
	if x != nil {
		return x.StaticDir
	}
	return ""
}

// 验证码配置
type Sms_VerificationCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`                     // 验证码长度, 默认6
	Expire        string                 `protobuf:"bytes,2,opt,name=expire,proto3" json:"expire,omitempty"`                      // 过期时间, 如 "5m", "10m"
	MaxRetry      int32                  `protobuf:"varint,3,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"` // 用户最大重试次数
	Debug         bool                   `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`                       // 调试模式, 打印验证码到日志
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sms_VerificationCode) Reset() {
	*x = Sms_VerificationCode{}
	mi := &file_internal_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sms_VerificationCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms_VerificationCode) ProtoMessage() {}

func (x *Sms_VerificationCode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms_VerificationCode.ProtoReflect.Descriptor instead.
func (*Sms_VerificationCode) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Sms_VerificationCode) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Sms_VerificationCode) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

func (x *Sms_VerificationCode) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *Sms_VerificationCode) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

// 限流配置
type Sms_RateLimit struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxRequestsPerMinute int32                  `protobuf:"varint,1,opt,name=max_requests_per_minute,json=maxRequestsPerMinute,proto3" json:"max_requests_per_minute,omitempty"` // 每分钟最大请求数
	MaxRequestsPerHour   int32                  `protobuf:"varint,2,opt,name=max_requests_per_hour,json=maxRequestsPerHour,proto3" json:"max_requests_per_hour,omitempty"`       // 每小时最大请求数
	MaxRequestsPerDay    int32                  `protobuf:"varint,3,opt,name=max_requests_per_day,json=maxRequestsPerDay,proto3" json:"max_requests_per_day,omitempty"`          // 每天最大请求数
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Sms_RateLimit) Reset() {
	*x = Sms_RateLimit{}
	mi := &file_internal_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sms_RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms_RateLimit) ProtoMessage() {}

func (x *Sms_RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms_RateLimit.ProtoReflect.Descriptor instead.
func (*Sms_RateLimit) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Sms_RateLimit) GetMaxRequestsPerMinute() int32 {
	if x != nil {
		return x.MaxRequestsPerMinute
	}
	return 0
}

func (x *Sms_RateLimit) GetMaxRequestsPerHour() int32 {
	if x != nil {
		return x.MaxRequestsPerHour
	}
	return 0
}

func (x *Sms_RateLimit) GetMaxRequestsPerDay() int32 {
	if x != nil {
		return x.MaxRequestsPerDay
	}
	return 0
}

// 重试配置
type Sms_Retry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts   int32                  `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"` // 系统最大重试次数
	Backoff       string                 `protobuf:"bytes,2,opt,name=backoff,proto3" json:"backoff,omitempty"`                             // 退避策略, 如 "1s", "2s"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sms_Retry) Reset() {
	*x = Sms_Retry{}
	mi := &file_internal_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sms_Retry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms_Retry) ProtoMessage() {}

func (x *Sms_Retry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms_Retry.ProtoReflect.Descriptor instead.
func (*Sms_Retry) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{5, 2}
}

func (x *Sms_Retry) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Sms_Retry) GetBackoff() string {
	if x != nil {
		return x.Backoff
	}
	return ""
}

var File_internal_conf_conf_proto protoreflect.FileDescriptor

const file_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x18internal/conf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xc6\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12!\n" +
	"\x03jwt\x18\x03 \x01(\v2\x0f.kratos.api.JWTR\x03jwt\x12!\n" +
	"\x03log\x18\x04 \x01(\v2\x0f.kratos.api.LogR\x03log\x12!\n" +
	"\x03sms\x18\x05 \x01(\v2\x0f.kratos.api.SmsR\x03sms\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xd5\x05\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12\x10\n" +
	"\x03dsn\x18\x03 \x01(\tR\x03dsn\x12,\n" +
	"\x05kafka\x18\x04 \x01(\v2\x16.kratos.api.Data.KafkaR\x05kafka\x122\n" +
	"\astorage\x18\x05 \x01(\v2\x18.kratos.api.Data.StorageR\astorage\x1a\x94\x02\n" +
	"\bDatabase\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12\"\n" +
	"\rmax_idle_conn\x18\x05 \x01(\x05R\vmaxIdleConn\x12\"\n" +
	"\rmax_open_conn\x18\x06 \x01(\x05R\vmaxOpenConn\x12\"\n" +
	"\rmax_idle_time\x18\a \x01(\x05R\vmaxIdleTime\x12<\n" +
	"\x1aslow_threshold_millisecond\x18\b \x01(\x03R\x18slowThresholdMillisecond\x1ad\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x12\x1b\n" +
	"\tpool_size\x18\x04 \x01(\x05R\bpoolSize\x1aM\n" +
	"\x05Kafka\x12\x14\n" +
	"\x05hosts\x18\x01 \x01(\tR\x05hosts\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x1a(\n" +
	"\aStorage\x12\x1d\n" +
	"\n" +
	"static_dir\x18\x01 \x01(\tR\tstaticDir\"5\n" +
	"\x03JWT\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\tR\x06expire\"\xdc\x01\n" +
	"\x03Log\x12\x1a\n" +
	"\bdirector\x18\x01 \x01(\tR\bdirector\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12%\n" +
	"\x0estacktrace_key\x18\x04 \x01(\tR\rstacktraceKey\x12!\n" +
	"\fencode_level\x18\x05 \x01(\tR\vencodeLevel\x12$\n" +
	"\x0elog_in_console\x18\x06 \x01(\bR\flogInConsole\x12\x1b\n" +
	"\tshow_line\x18\a \x01(\bR\bshowLine\"\xcf\x05\n" +
	"\x03Sms\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11access_key_secret\x18\x02 \x01(\tR\x0faccessKeySecret\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tsign_name\x18\x04 \x01(\tR\bsignName\x12#\n" +
	"\rtemplate_code\x18\x05 \x01(\tR\ftemplateCode\x12M\n" +
	"\x11verification_code\x18\x06 \x01(\v2 .kratos.api.Sms.VerificationCodeR\x10verificationCode\x128\n" +
	"\n" +
	"rate_limit\x18\a \x01(\v2\x19.kratos.api.Sms.RateLimitR\trateLimit\x12+\n" +
	"\x05retry\x18\b \x01(\v2\x15.kratos.api.Sms.RetryR\x05retry\x1au\n" +
	"\x10VerificationCode\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\tR\x06expire\x12\x1b\n" +
	"\tmax_retry\x18\x03 \x01(\x05R\bmaxRetry\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debug\x1a\xa6\x01\n" +
	"\tRateLimit\x125\n" +
	"\x17max_requests_per_minute\x18\x01 \x01(\x05R\x14maxRequestsPerMinute\x121\n" +
	"\x15max_requests_per_hour\x18\x02 \x01(\x05R\x12maxRequestsPerHour\x12/\n" +
	"\x14max_requests_per_day\x18\x03 \x01(\x05R\x11maxRequestsPerDay\x1aD\n" +
	"\x05Retry\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\vmaxAttempts\x12\x18\n" +
	"\abackoff\x18\x02 \x01(\tR\abackoffB%Z#kratos-realworld/internal/conf;confb\x06proto3"

var (
	file_internal_conf_conf_proto_rawDescOnce sync.Once
	file_internal_conf_conf_proto_rawDescData []byte
)

func file_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)))
	})
	return file_internal_conf_conf_proto_rawDescData
}

var file_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),            // 0: kratos.api.Bootstrap
	(*Server)(nil),               // 1: kratos.api.Server
	(*Data)(nil),                 // 2: kratos.api.Data
	(*JWT)(nil),                  // 3: kratos.api.JWT
	(*Log)(nil),                  // 4: kratos.api.Log
	(*Sms)(nil),                  // 5: kratos.api.Sms
	(*Server_HTTP)(nil),          // 6: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),          // 7: kratos.api.Server.GRPC
	(*Data_Database)(nil),        // 8: kratos.api.Data.Database
	(*Data_Redis)(nil),           // 9: kratos.api.Data.Redis
	(*Data_Kafka)(nil),           // 10: kratos.api.Data.Kafka
	(*Data_Storage)(nil),         // 11: kratos.api.Data.Storage
	(*Sms_VerificationCode)(nil), // 12: kratos.api.Sms.VerificationCode
	(*Sms_RateLimit)(nil),        // 13: kratos.api.Sms.RateLimit
	(*Sms_Retry)(nil),            // 14: kratos.api.Sms.Retry
	(*durationpb.Duration)(nil),  // 15: google.protobuf.Duration
}
var file_internal_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.jwt:type_name -> kratos.api.JWT
	4,  // 3: kratos.api.Bootstrap.log:type_name -> kratos.api.Log
	5,  // 4: kratos.api.Bootstrap.sms:type_name -> kratos.api.Sms
	6,  // 5: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	7,  // 6: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	8,  // 7: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	9,  // 8: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	10, // 9: kratos.api.Data.kafka:type_name -> kratos.api.Data.Kafka
	11, // 10: kratos.api.Data.storage:type_name -> kratos.api.Data.Storage
	12, // 11: kratos.api.Sms.verification_code:type_name -> kratos.api.Sms.VerificationCode
	13, // 12: kratos.api.Sms.rate_limit:type_name -> kratos.api.Sms.RateLimit
	14, // 13: kratos.api.Sms.retry:type_name -> kratos.api.Sms.Retry
	15, // 14: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	15, // 15: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_conf_conf_proto_init() }
func file_internal_conf_conf_proto_init() {
	if File_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_internal_conf_conf_proto = out.File
	file_internal_conf_conf_proto_goTypes = nil
	file_internal_conf_conf_proto_depIdxs = nil
}
